# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfjvmaqHG4PVClbkiAGB0KtWKI77w-bq
"""

# =========================================
# House Price Prediction using ML
# Algorithm : Linear Regression
# =========================================

# STEP 1 — Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# STEP 2 — Read Dataset

data = pd.read_csv("/content/train.csv")

print("Dataset Preview")
print(data.head(10))

print("\nShape of Dataset")
print(data.shape)

print("\nNull Values")
print(data.isnull().sum())

# STEP 3 — Define Input and Output

features = data[['OverallQual',
                 'GrLivArea',
                 'GarageCars',
                 'TotalBsmtSF',
                 'YearBuilt',
                 'FullBath',
                 'BedroomAbvGr',
                 'LotArea']]

target = data['SalePrice']

# STEP 4 — Split Dataset

x_train, x_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.25,
    random_state=10
)

print("\nTraining Data Shape :", x_train.shape)
print("Testing Data Shape  :", x_test.shape)

# STEP 5 — Create and Train Model

lr_model = LinearRegression()

lr_model.fit(x_train, y_train)

print("\nModel Successfully Trained")

# STEP 6 — Predict House Prices

predictions = lr_model.predict(x_test)

print("\nSample Predictions")
print(predictions[:10])

# STEP 7 — Evaluate Model

MAE = mean_absolute_error(y_test, predictions)

MSE = mean_squared_error(y_test, predictions)

RMSE = np.sqrt(MSE)

R2 = r2_score(y_test, predictions)

print("\nEvaluation Metrics")
print("Mean Absolute Error :", MAE)
print("Mean Squared Error  :", MSE)
print("Root Mean Squared Error :", RMSE)
print("R2 Score :", R2)

# STEP 8 — Actual vs Predicted Table

comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": predictions
})

print("\nActual vs Predicted Prices")
print(comparison.head(10))

# STEP 9 — Visualization

plt.figure(figsize=(7,5))

plt.scatter(y_test, predictions)

plt.xlabel("Actual House Prices")
plt.ylabel("Predicted House Prices")

plt.title("Actual vs Predicted Prices")

plt.show()

# STEP 10 — Feature Coefficients

importance = pd.DataFrame({
    "Features": features.columns,
    "Values": lr_model.coef_
})

print("\nFeature Importance")
print(importance)

# STEP 11 — Correlation Heatmap

plt.figure(figsize=(12,8))

numeric_data = data.select_dtypes(include='number')

sns.heatmap(numeric_data.corr(),
            annot=True,
            linewidths=0.5,
            fmt='.2f')

plt.title("Feature Correlation Heatmap")

plt.show()